### ISSUE TITLE
[BUG?] Cannot login

### ISSUE THREAD

**Issue by Yarosvet** [solsticegamestudios/steam#4]
```python
from steam.client import SteamClient


s = SteamClient()
s.verbose_debug = True
s.login("my_user", "my_password")

print("Logged on as: %s" % s.user.name)
print("Community profile: %s" % s.steam_id.community_url)
print("Last logon: %s" % s.user.last_logon)
print("Last logoff: %s" % s.user.last_logoff)
print("Number of friends: %d" % len(s.friends))

s.logout()
```

But `s.logged_on` is `False` and no info from account loaded in SteamClient. What am I doing wrong? Or it's a bug

**Comment by WinterPhoenix** [comment]
Will review once we've finished migrating to only supporting Python 3.7+, and have tests working properly again

**Comment by WinterPhoenix** [comment]
Tests don't completely work right yet, but try again with that PR merge and let us know
